apiVersion: v1
kind: Pod
metadata: 
  name: client-pod
  labels: 
    component: web
spec:
  containers: 
    - name: client
      image: validationweb
      imagePullPolicy: Never
      ports:
        - containerPort: 80

# pull from local docker images
# eval $(minikube docker-env)
# docker build . -t validationweb
# imagePullPolicy: Never